<?php

namespace Tests\Browser;

use Illuminate\Support\Facades\Artisan;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class BrowserFormulairesPageTest extends DuskTestCase
{


    public function test_browser_edit_formulaires(){
        $this->browse(function (Browser $browser) {
            $browser->resize(1920, 2000);
            $browser->visit('/admin/login')
                ->type('email', 'email00@blop.fr')
                ->type('password', 'password00')
                ->clickButtonWithId("login")
                ->assertSee('Dashboard')
                ->visit('admin/formulaires')
                ->assertSee('Gestion des formulaires')
                ->clickLinkWithId('edit_formulaire_1')
                ->assertSee('Editer le formulaire : Nous contacter (CONTACT)')
                ->type('email_from', 'test@ideal-com.com')
                ->clickInputWithId('editer')
                ->assertUrlIs($this->getUrlFormulairesIndex())
                ->assertSee('Vous avez bien édité le formulaire !');;
        });
    }


    public function test_browser_redirect_field_page(){
        $this->browse(function (Browser $browser) {
            $browser->resize(1920, 2000);
            $browser->visit('admin/formulaires')
                ->assertSee('Gestion des formulaires')
                ->clickLink('Champs')
                ->assertUrlIs($this->getUrlFieldsIndex(1));
        });
    }



    /**
     * Reset database and session
     *
     */
    public function tearDown()
    {
        session()->flush();
        Artisan::call('migrate:refresh');
        Artisan::call('db:seed');
        parent::tearDown(); // TODO: Change the autogenerated stub

    }

}
