<?php
/**
 * Created by PhpStorm.
 * User: dqminh
 * Date: 15/05/2018
 * Time: 18:14
 */

namespace Tests;

use Illuminate\Support\Facades\Auth;
use Laravel\BrowserKitTesting\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class RouteTestCase extends BaseTestCase
{
    use CreatesApplicationWithAuth;
    public $baseUrl = 'http://localhost';

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate:refresh');
        Artisan::call('db:seed');
    }

    public function tearDown()
    {

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}