<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    //use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate:refresh');
        Artisan::call('db:seed');
        $this->migrated = true;
    }

    public function tearDown()
    {

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
